services:
    open-elevation:
        restart: unless-stopped
        platform: linux/amd64
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        volumes:
            - "./data:/code/data"
            - "./certs:/code/certs"
        environment:
            - PYTHONUNBUFFERED=1
        command: stdbuf -i0 -o0 -e0 python3 server.py
        ports:
            - 9080:8080